version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:8

  api:
    platform: linux/x86_64
    restart: always
    volumes:
      - ./scripts:/app/scripts
      - ./server:/app/server
      - /app/server/node_modules/
