version: '3.8'

services:
  db:
    environment:
      MYSQL_DATABASE: 'momentum_test'
      MYSQL_USER: 'mom_test'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'

  api:
    restart: "no"
    environment:
      MOM_STORAGE_USE_LOCAL: "true"
      NODE_ENV: 'test'
    volumes:
      - ./scripts:/app/scripts
      - ./server:/app/server
      - /app/server/node_modules/
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    entrypoint: "npm run test-docker"
    ports:
      - 3003:3002
